import mongoose from "mongoose";

/**
 * Transaction Schema
 * 
 * Field Explanations:
 * - date: User-selected transaction date (when the transaction actually occurred)
 *   IMPORTANT: This is NOT the same as createdAt. The user should be able to select
 *   any date (past, present) for their transaction. This field stores THAT date.
 * 
 * - createdAt/updatedAt: Automatic timestamps provided by Mongoose (timestamps: true)
 *   These are auto-generated by MongoDB and cannot be edited by the user.
 *   Use these for "when was this record created/updated in the database"
 */
const transactionSchema = new mongoose.Schema(
  {
    userId: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "User",
      required: true 
    },
    type: { 
      type: String, 
      required: true,
      enum: ['income', 'expense']
    },
    category: { 
      type: String, 
      required: true 
    },
    amount: { 
      type: Number, 
      required: true 
    },
    /** 
     * date: User-selected transaction date
     * 
     * This stores WHEN the user says the transaction occurred
     * (e.g., user selects "January 15, 2024" even if today is March 2024)
     * 
     * KEY POINT: This field has NO default value. We want Mongoose to accept
     * whatever date the user sends. If no date is provided, the controller
     * should handle the default, NOT the schema.
     */
    date: {
      type: Date,
      required: false, // Controller will handle default if not provided
    },
  },
  {
    // timestamps: true adds createdAt and updatedAt automatically
    // These are managed by MongoDB, NOT by user input
    timestamps: true,
  },
);

// Index for faster queries by user and date
transactionSchema.index({ userId: 1, date: -1 });

export default mongoose.model("Transaction", transactionSchema);
